/* Copyright (C) 2023 Harry Clark */

/* dinput8 Implementation of WUP-028 for Sonic Heroes */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE WUP-028 DRIVER */

/* NESTED INCLUDES */

#include "wup028.h"

/* CHECK FOR ERROR HANDLING SCHEME UPON INTILISATION */
/* THIS IS TAKING INTO ACCOUNT THE LOAD ASYNCHRONOUS METHOD */
/* BEFORE INITIALISING THE MASTER COMPONENT */

static IPC::PAD_INIT* PAD_INIT(IPC::PAD_READ* PAD_READ, PAD::PAD_ERROR* ERROR,
	                                          IOS::IOS_OPEN_ASYNC* OPEN_ASYNC)
{
	for (U32 i = 0; i < WUP_PORT; i++)
	{
		ERROR += WUP_PORT;
	}

	OPEN_ASYNC(WUP_PATH, NULL);
}