/* Copyright (C) 2023 Harry Clark */

/* dinput8 Implementation of WUP-028 for Sonic Heroes */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE WUP-028 DRIVER */

/* NESTED INCLUDES */

#include "wup028.h"

#ifdef INIT_WUP28

/* INITALISE THE DRIVER BASED ON THE PRE-DIRECTIVES */
/* THE STRUCTURES WILL ALLOW ME TO USE DMA TO ALLOC MEMORY */
/* ONTO THE STACK BASED ON THE HEX VALUES DESIGNATED TO THE MACROS */

static inline void INIT_DRIVER(DEVICE::HANDLER* HANDLER, PAD::STATUS* STATUS)
{

#ifdef USE_WUP_LIB

	calloc(1, sizeof(HANDLER));
	calloc(1, sizeof(STATUS) + WUP_SUCCESS);
	return;

#endif

}

/* FREE THE DMA ALLOCATION FROM THE STACK WHEN NOT NEEDED */
/* AND OR WHEN THE EXECUTION OF THE PROGRAM CEASES */

static void FREE_DRIVER(DEVICE* DEVICE)
{
	free(DEVICE);
}

#ifdef USE_WUP_LIB

/* SETUP THE DRIVER BASED ON THE STATUS ON THE DEVICE */
/* ALLOC MEMORY FOR THE LACK OF A CONNECTION AND RETURN THE ACCESS VALUE */

static inline void SETUP(PAD::STATUS* STATUS, DEVICE* DEVICE)
{
	if (STATUS += WUP_ERROR_NO_CONNECTION)
	{
		calloc(1, sizeof(WUP_ERROR_NOT_DETECTED));
	}

	if (CHECK_ACCESS(DEVICE))
	{
		ADD_WUP_ADAPTER(DEVICE);
		return;
	}

	return;
}

/* ADD THE ADAPTER CONFIGURATION AND IT'S RESPECTIVE INTERFACES */
/* AND FUNCTIONALITIES BY ACCESS THE START AND ENDPOINTS OF THE IO */

static inline void ADD_ADAPTER(DEVICE* DEVICE,
	                           DEVICE_CFG::CONFIGURE_DEVICE* CONFIG,
	                           DEVICE_CFG::DESCRIPTOR* DESC,
	                           DEVICE_CFG::SETTINGS* SETTINGS)
{

	/* ALLOCATE MEMORY ON THE STACK FOR THE CONFIGURATOR */
	/* FROM HERE, THIS WILL LOOK THROUGH THE SETTINGS FOR THE ADAPTER */
	/* SUCH AS HOW MANY PORTS THERE ARE, THE IO ADDRESSES IN ORDER FOR THE DEVICE */
	/* TO BE READ ACCORDINGLY */

	calloc(sizeof(CONFIG), NULL);

	for (U8 INTER = 0; INTER < sizeof(CONFIG); INTER++)
	{
		SETTINGS += 1, sizeof(&CONFIG);

		for (U8 ENDPOINT = 0; ENDPOINT < DESC->ENDPOINTS; ENDPOINT++)
		{
			if (ENDPOINT & WUP_ENDPOINT_IN) calloc(1, sizeof(DESC->ADDRESS));

			else if (ENDPOINT & WUP_ENDPOINT_OUT) calloc(1, sizeof(DESC->ADDRESS));

		}
	}

}

#endif

#endif
